### ISSUE TITLE
What's the main reason that this is based off the Go interface?

### ISSUE THREAD

**Issue by hencrice** [neithanmo/fluent-bit-rs#3]
Hey @neithanmo could you elaborate on why this is based off the Go header interface instead of the [C interface](https://github.com/fluent/fluent-bit/blob/master/include/fluent-bit/flb_output.h#L57)?

**Comment by neithanmo** [comment]
Hi @hencrice, It is based on the C , this interface was built with to objective to make a bit easier the interaction of the fluent-bit's C API plugin with the Go API plugin., without it building plugins in Go(or any other language) would be pretty difficult.
The fluent-bit-rs uses this interface, which is at the end a simplified version of the C API, to interact with the fluent-bit engine, that's why we need to enable this feature in the fluent-bit side. :)
